create table catalog (
  id                            bigint generated by default as identity (start with 1)  not null,
  last_modified_at              timestamp,
  created_at                    timestamp,
  uniqueness_hash               bigint,
  uid                           varchar(255),
  name                          varchar(255),
  version                       bigint not null,
  constraint pk_catalog primary key (id)
);

create table catalog_version (
  id                            bigint generated by default as identity (start with 1)  not null,
  last_modified_at              timestamp,
  created_at                    timestamp,
  uniqueness_hash               bigint,
  uid                           varchar(255),
  name                          varchar(255),
  synchronizationtarget_id      bigint,
  catalog_id                    bigint not null,
  version                       bigint not null,
  constraint pk_catalog_version primary key (id)
);

create index ix_catalog_version_catalog_id on catalog_version (catalog_id);
alter table catalog_version add constraint fk_catalog_version_catalog_id foreign key (catalog_id) references catalog (id) on delete restrict on update restrict;

